apiVersion: v1
kind: Secret
metadata:
  name: teknoloji-secret
  namespace: teknoloji-haberleri
  labels:
    app.kubernetes.io/name: teknoloji-haberleri
type: Opaque
stringData:
  # !! DEPLOY ONCESI BU DEGERLERI DEGISTIRIN !!
  SECRET_KEY: "buraya-guclu-rastgele-secret-key-yazin-min-50-karakter"
  DB_USER: "cybernews"
  DB_PASSWORD: "buraya-guclu-sifre-yazin"
  POSTGRES_PASSWORD: "buraya-guclu-sifre-yazin"
